image: node:12

stages:
  - release

cache:
  paths:
  - node_modules/

build:
  stage: release
  only:
    - master
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends jq
    - npm ci
  script:
    - ./ci-release.sh
